### ISSUE TITLE
Fibonacci (Feature Request)

### ISSUE THREAD

**Issue by google0101-ryan** [baskiton/lsc-8#1]
I am amazed by this project. I have but one request: The Fibonacci Sequence. This is the ultimate test of a computer, and it would be really cool to see this computer execute it.

**Comment by baskiton** [comment]
Thank you for contacting! The example has been added to the repository.
![image](https://user-images.githubusercontent.com/40061352/113402465-3d3f3d00-93cf-11eb-89a8-8705cb2b1ba2.png)
