### ISSUE TITLE
unable to run ?

### ISSUE THREAD

**Issue by luoxin13** [baskiton/lsc-8#2]
Thanks for your nice work! I have tried to simulate the circuit in Logisim2.7.1.
However, after loading the ROM data, pressing "on" button, starting simulation,
the computer seems not running. How can I debug the problem?

**Comment by baskiton** [comment]
Hello!
Make sure simulation and ticks are enabled:
 * _Simulate -> Simulation Enabled_
 * _Simulate -> Ticks Enabled_

The frequency is maxed out:
 * _Simulate -> Tick Frequency -> 4.1 KHz_

Also enable frequency display:
 * _File -> Preferences -> Window -> Show tick rate_

After pressing the "ON" button, you should see a decrease in the frequency of ticks

**Comment by luoxin13** [comment]
![image](https://github.com/baskiton/lsc-8/assets/96218122/a206af8b-29c3-4691-b8ba-5ae1001a2baf)

yes, I did do the above operations. But it seems the LCD displayed nothing.

**Comment by baskiton** [comment]
520 Hz is so slowly, but after a while messages should appear on the screen.
What ROM did you download your data into? BIOS or "Removable Storage"?

**Comment by luoxin13** [comment]
I download it into BIOS Rom

**Comment by baskiton** [comment]
If you wrote it yourself, it's probably a bug in the code.
If it is `rom/fibo.rom` or `rom/hello-world.rom` from the repository, then they need to be loaded to "Removable Storage".
Try restoring the BIOS by loading the `rom/8kBIOS.rom` file from the repository into it

**Comment by luoxin13** [comment]
Thanks for your timely reply! I shall try it right now.
